#
# Terraform GitHub Actions Workflow
#
# This workflow automates the deployment and validation of Terraform configurations using GitHub Actions.
#
# Workflow Triggers:
# - Runs on push events to the `main` branch.
# - Runs on pull requests.
#
# Permissions:
# - Grants required permissions for OIDC authentication, repository content access, pull request comments, security events, and actions.
#
# Environment Variables:
# - TF_LOG: Sets Terraform logging level.
# - AWS_REGION: AWS region, sourced from repository secrets.
# - GITHUB_TOKEN: GitHub token for authentication.
#
# Job: deploy
# - Runs on Ubuntu latest.
# - Sets working directory to `/terraform/`.
#
# Steps:
# 1. Checks out repository code.
# 2. Configures AWS credentials using OIDC and secrets.
# 3. Sets up Terraform CLI.
# 4. Checks Terraform formatting (`terraform fmt`).
# 5. Initializes Terraform with backend configuration from secrets.
# 6. Validates Terraform configuration.
# 7. Installs and runs TFLint for Terraform linting.
# 8. Posts TFLint results as a comment on pull requests.
# 9. Outputs TFLint results to logs.
# 10. Runs `terraform plan` on pull requests.
# 11. Runs Checkov for security and compliance scanning, outputs SARIF for GitHub Security tab.
# 12. Uploads SARIF results for code scanning.
# 13. Posts Terraform validation and plan results as a comment on pull requests.
# 14. Fails the workflow if `terraform plan` fails.
# 15. Applies Terraform changes automatically on push to `main`.
#
# Notes:
# - Secrets required: AWS_REGION, AWS_ROLE, AWS_SOURCE_ACCOUNT_ID, AWS_BUCKET_NAME, AWS_BUCKET_KEY_NAME, GITHUB_TOKEN.
# - Uses OIDC for secure AWS authentication.
# - Provides detailed feedback on pull requests via comments.
# - Integrates security scanning and code quality checks.
#
name: "Terraform action"
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  id-token: write
  contents: read
  pull-requests: write
  security-events: write
  actions: read
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /terraform/
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          source-account-id: ${{ secrets.AWS_SOURCE_ACCOUNT_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true

      - id: tflint
        run: tflint -f compact
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.tflint.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Lint 📖\`${{ steps.tflint.outcome }}\`
            
            <details><summary>TFLint Summary</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - run: echo ${{ steps.tflint.outputs.stdout }}
      - run: echo ${{ steps.tflint.outputs.stderr }}
      - run: echo ${{ steps.tflint.outputs.exitcode }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        if: github.event_name == 'pull_request'

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
            
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
            
            </details>
            
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
